/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Classes;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Andrés Castro
 */
public class MainUI extends javax.swing.JFrame {
    public BattleSimulation simulation;
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        Studio StudioNK = new Studio("NK");
        Studio StudioCN = new Studio("CN");
        AI ai = new AI();
        Administrator admin = new Administrator(StudioNK, StudioCN);
        this.simulation = new BattleSimulation(ai, admin);
        
        
        admin.chooseCharacter(ai);
        this.simulation.start();
        
        IAtim.setText(Integer.toString(this.simulation.ai.time));
        while (true){
            if (this.simulation.ai.CharA != null) {   
                try {
                    IAState.setText(this.simulation.ai.state);
                    ImgCharA.setIcon(new ImageIcon(ImageIO.read(new File(this.simulation.ai.CharA.charImage))));
                    ImgCharB.setIcon(new ImageIcon(ImageIO.read(new File(this.simulation.ai.CharB.charImage))));
                    CharAName.setText(this.simulation.ai.CharA.name);
                    CharBName.setText(this.simulation.ai.CharB.name);
                    CharAHealth.setText(Integer.toString(this.simulation.ai.CharA.health));
                    CharBHealth.setText(Integer.toString(this.simulation.ai.CharB.health));
                    CharASkill.setText(Integer.toString(this.simulation.ai.CharA.skill));
                    CharBSkill.setText(Integer.toString(this.simulation.ai.CharB.skill));
                    CharAAgility.setText(Integer.toString(this.simulation.ai.CharA.agility));
                    CharBAgility.setText(Integer.toString(this.simulation.ai.CharB.agility));
                    CharAStrength.setText(Integer.toString(this.simulation.ai.CharA.strength));
                    CharBStrength.setText(Integer.toString(this.simulation.ai.CharB.strength));
                    
                    showCola1.setText(this.simulation.StudioNK.cola1.showCola());
                    showCola2.setText(this.simulation.StudioNK.cola2.showCola());
                    showCola3.setText(this.simulation.StudioNK.cola3.showCola());
                    showCola4.setText(this.simulation.StudioCN.cola1.showCola());
                    showCola5.setText(this.simulation.StudioCN.cola2.showCola());
                    showCola6.setText(this.simulation.StudioCN.cola3.showCola());
                    
                    winsNK.setText(Integer.toString(this.simulation.StudioNK.winners.getSize()));
                    winsCN.setText(Integer.toString(this.simulation.StudioCN.winners.getSize()));
                    
                    
                    if ("Decidiendo resultado".equals(this.simulation.ai.state)) {
                        if (this.simulation.ai.stateInt == 1) {
                            jTextArea2.setText(jTextArea2.getText() + "\n\n" + this.simulation.ai.startText + "\n");
                            this.simulation.ai.stateInt = 0;
                        }  
                    } else {
                        if (this.simulation.ai.stateInt == 1) {
                            jTextArea2.setText(this.simulation.ai.startText + "\n" + this.simulation.ai.announceText + this.simulation.ai.finalText );
                            this.simulation.ai.announceText = "";
                            this.simulation.ai.stateInt = 0;
                        }
                    }
                    
                    
                  
                    
                } catch (IOException ex) {
                    Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                }  
            }    
        }
        
    }

    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgCharA = new javax.swing.JLabel();
        ImgCharB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CharAName = new javax.swing.JLabel();
        CharBName = new javax.swing.JLabel();
        CharAStrength = new javax.swing.JLabel();
        CharBHealth = new javax.swing.JLabel();
        CharAHealth = new javax.swing.JLabel();
        CharBSkill = new javax.swing.JLabel();
        CharASkill = new javax.swing.JLabel();
        CharBAgility = new javax.swing.JLabel();
        CharAAgility = new javax.swing.JLabel();
        CharBStrength = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IAState = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        showCola6 = new javax.swing.JLabel();
        showCola5 = new javax.swing.JLabel();
        showCola4 = new javax.swing.JLabel();
        showCola3 = new javax.swing.JLabel();
        showCola2 = new javax.swing.JLabel();
        showCola1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        winsCN = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        winsNK = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        IAtim = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImgCharA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Avatar/Azula.png"))); // NOI18N
        ImgCharA.setText("jLabel4");
        getContentPane().add(ImgCharA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 280, 280));

        ImgCharB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Avatar/Azula.png"))); // NOI18N
        ImgCharB.setText("jLabel4");
        getContentPane().add(ImgCharB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 400, 280, 280));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Skill.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 30, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Agility.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, 30, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Strength.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 30, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Health.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 30, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Health.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Skill.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Agility.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Strength.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        CharAName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharAName.setForeground(new java.awt.Color(0, 0, 0));
        CharAName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CharAName.setText("Name");
        getContentPane().add(CharAName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 270, 50));

        CharBName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharBName.setForeground(new java.awt.Color(0, 0, 0));
        CharBName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CharBName.setText("Name");
        getContentPane().add(CharBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 670, 270, 50));

        CharAStrength.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharAStrength.setForeground(new java.awt.Color(0, 0, 0));
        CharAStrength.setText("0");
        getContentPane().add(CharAStrength, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 50, 50));

        CharBHealth.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharBHealth.setForeground(new java.awt.Color(0, 0, 0));
        CharBHealth.setText("0");
        getContentPane().add(CharBHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, 50, 30));

        CharAHealth.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharAHealth.setForeground(new java.awt.Color(0, 0, 0));
        CharAHealth.setText("0");
        getContentPane().add(CharAHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 50, 30));

        CharBSkill.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharBSkill.setForeground(new java.awt.Color(0, 0, 0));
        CharBSkill.setText("0");
        getContentPane().add(CharBSkill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, 50, 50));

        CharASkill.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharASkill.setForeground(new java.awt.Color(0, 0, 0));
        CharASkill.setText("0");
        getContentPane().add(CharASkill, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 50, 50));

        CharBAgility.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharBAgility.setForeground(new java.awt.Color(0, 0, 0));
        CharBAgility.setText("0");
        getContentPane().add(CharBAgility, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 470, 50, 50));

        CharAAgility.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharAAgility.setForeground(new java.awt.Color(0, 0, 0));
        CharAAgility.setText("0");
        getContentPane().add(CharAAgility, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 50, 50));

        CharBStrength.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CharBStrength.setForeground(new java.awt.Color(0, 0, 0));
        CharBStrength.setText("0");
        getContentPane().add(CharBStrength, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Regular_Show_Logo.svg_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 230, 110));

        IAState.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        IAState.setForeground(new java.awt.Color(255, 255, 255));
        IAState.setText("Estado");
        getContentPane().add(IAState, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cola 3");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Control de Tiempos:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        showCola6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showCola6.setForeground(new java.awt.Color(255, 255, 255));
        showCola6.setText("Cola 1");
        getContentPane().add(showCola6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, 280, 30));

        showCola5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showCola5.setForeground(new java.awt.Color(255, 255, 255));
        showCola5.setText("Cola 1");
        getContentPane().add(showCola5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 280, 30));

        showCola4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showCola4.setForeground(new java.awt.Color(255, 255, 255));
        showCola4.setText("Cola 1");
        getContentPane().add(showCola4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 280, 30));

        showCola3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showCola3.setForeground(new java.awt.Color(255, 255, 255));
        showCola3.setText("Cola 1");
        getContentPane().add(showCola3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 280, 30));

        showCola2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showCola2.setForeground(new java.awt.Color(255, 255, 255));
        showCola2.setText("Cola 1");
        getContentPane().add(showCola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 280, 30));

        showCola1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showCola1.setForeground(new java.awt.Color(255, 255, 255));
        showCola1.setText("Cola 1");
        getContentPane().add(showCola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 280, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cola 2");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cola 3");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 280, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cola 1");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 140, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Cola 2");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 210, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Estado de la IA:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        winsCN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        winsCN.setForeground(new java.awt.Color(255, 255, 255));
        winsCN.setText("0");
        getContentPane().add(winsCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 80, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cola 1");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Wins:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Wins:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, -1, -1));

        winsNK.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        winsNK.setForeground(new java.awt.Color(255, 255, 255));
        winsNK.setText("0");
        getContentPane().add(winsNK, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 90, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, -1));

        IAtim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IAtimActionPerformed(evt);
            }
        });
        getContentPane().add(IAtim, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 64, 22));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 280, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Avatar_the_Last_Airbender_logo_PNG_(12).png"))); // NOI18N
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 110));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 470, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/PngItem_6002639 (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 540, 214));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 470, 170));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interface/Stage.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IAtimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IAtimActionPerformed

    }//GEN-LAST:event_IAtimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.simulation.ai.time = Integer.parseInt(IAtim.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CharAAgility;
    private javax.swing.JLabel CharAHealth;
    private javax.swing.JLabel CharAName;
    private javax.swing.JLabel CharASkill;
    private javax.swing.JLabel CharAStrength;
    private javax.swing.JLabel CharBAgility;
    private javax.swing.JLabel CharBHealth;
    private javax.swing.JLabel CharBName;
    private javax.swing.JLabel CharBSkill;
    private javax.swing.JLabel CharBStrength;
    private javax.swing.JLabel IAState;
    private javax.swing.JTextField IAtim;
    private javax.swing.JLabel ImgCharA;
    private javax.swing.JLabel ImgCharB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel showCola1;
    private javax.swing.JLabel showCola2;
    private javax.swing.JLabel showCola3;
    private javax.swing.JLabel showCola4;
    private javax.swing.JLabel showCola5;
    private javax.swing.JLabel showCola6;
    private javax.swing.JLabel winsCN;
    private javax.swing.JLabel winsNK;
    // End of variables declaration//GEN-END:variables
}
